name: Update Streak Stats SVG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Streak Stats SVG
        uses: denvercoder1/github-readme-streak-stats@main
        with:
          username: ${{ github.repository_owner }}
          theme: tokyonight
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Move and Commit Changes
        run: |
          # Move o arquivo gerado automaticamente para a raiz do repositório
          mv /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/generated/streak-stats.svg ./streak-stats.svg || mv ./generated/streak-stats.svg ./streak-stats.svg || true
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add streak-stats.svg
          git commit -m "Update GitHub streak stats visual" || exit 0
          git push
