name: Update Streak Stats SVG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Streak Stats SVG
        uses: denvercoder1/github-readme-streak-stats@main
        with:
          username: ${{ github.repository_owner }}
          theme: tokyonight
          # AJUSTADO: Aponta diretamente para o arquivo na raiz
          path: ./streak-stats.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
